#ifndef TREE_ERRORS_H
#define TREE_ERRORS_H

enum treeErrorCode {
    NO_TREE_ERRORS,
    ALLOC_MEMORY_ERROR,
    TREE_LINK_ERROR,
    TREE_NO_ROOT,
    WRONG_TREE_SYNTAX,
    FILE_DESCRIPTOR_ERROR,
    FILE_SIZE_ERROR,
    BUFFER_CTOR_ERROR,
    FILE_READ_ERROR,
    INPUT_FILE_OPEN_ERROR,
    NULL_SEGMENT_POINTER,
    CREATE_OUTPUT_FILE_ERROR,
    WRITE_TO_OUTPUT_FILE_ERROR,
    NULL_SEGMENT_DATA_ERROR,
    DIFFERENT_SEGMENT_TYPES,
    NO_GRAPHVIZ_LIB_ERROR
};

void print_tree_error(treeErrorCode error);

void print_tree_error_message(treeErrorCode error, FILE* stream);

#endif